spring:
 application:
  name: discovery-service

server:
  port: 8761

# by default this service also gets listed in the dashboard; you can disable it by turning off the registration
eureka:
  client:
    register-with-eureka: false  