spring:
  application:
    name: gateway-service
server:
 port: 7000    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api/v1
  routes:
   math-api:
    strip-prefix: true
    path: /math/**  